### ISSUE TITLE
example.import_name.py throws error

### ISSUE THREAD

**Issue by Lukeluca** [cbess/inventory-checkin#6]
I get the following error when I try to run example.import_name.py:

Traceback (most recent call last):
  File "example.import_names.py", line 3, in <module>
    from webapp.models import Person
  File "/Users/devadmin/bookmate/webapp/models.py", line 1, in <module>
    from core import db
  File "/Users/devadmin/bookmate/core/**init**.py", line 1, in <module>
    from cherrypy import wsgiserver as cherrypy_wsgiserver
ImportError: No module named cherrypy

**Comment by cbess** [comment]
Make sure you run the script inside of the virtual env (`source env/bin/activate`). Step **5**.

**Comment by Lukeluca** [comment]
I get a different error when I run it in the virtual env:

/Users/devadmin/bookmate/inventorycheckin_env/lib/python2.7/site-packages/flask_cache/**init**.py:88: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
Traceback (most recent call last):
  File "example.import_names.py", line 3, in <module>
    from webapp.models import Person
  File "/Users/devadmin/bookmate/webapp/models.py", line 4, in <module>
    from server import app
  File "/Users/devadmin/bookmate/webapp/server.py", line 13, in <module>
    import views
  File "/Users/devadmin/bookmate/webapp/views.py", line 10, in <module>
    from forms import LoginForm
  File "/Users/devadmin/bookmate/webapp/forms.py", line 3, in <module>
    from models import User, INVENTORY_STATUS, InventoryGroup, InventoryItem
ImportError: cannot import name User

**Comment by cbess** [comment]
How are you running it (dir, prompt, etc)?

**Comment by Lukeluca** [comment]
commands after logging into user directory:

cd bookmate
source inventorycheckin_env/bin/activate
python example.import_names.py

**Comment by cbess** [comment]
Temporarily, comment out `webapp/server.py` line 13. Run the import, then uncomment that line. Restart app.

**Comment by cbess** [comment]
Also, side note, update the `CACHE_TYPE` setting value (to at least `simple`).

**Comment by Lukeluca** [comment]
It worked! Thanks!
